#!/usr/bin/env perl
use strict;
use warnings;
use POSIX qw(strftime);

my $f = $ARGV[0];
my %data;
my @fields;
$, = " ";

my $date = strftime "%y%m%d", localtime;

open FH, $f;
# read the first line and make an array of fields
my $first_line = <FH>;
chomp($first_line);
#$first_line =~ s/\$/\\\$/g;
my @marc_fields = split(/\t/, $first_line);


	while(<FH>){
		chomp;
		# splite line by \t and make an array
		@fields = split(/\t/);

		#if(@marc_fields eq @fields){

			# print the leader field
			
			print "=LDR  00000nam  2200000Ia 45e0\n";
			#	print "=008  ".$date."s9999||||xx\\||||||||||||||\\||und||\n";
			for my $i (0 .. $#fields){
				# split fields and sub fields
				my ($f, $sub_f)  = split(/\$/, $marc_fields[$i]);
				#$fields[$i] =~ s#'##g;
				$fields[$i] =~ s#"##g;
				$fields[$i] =~ s#”##g;
				$fields[$i] =~ s#“##g;
				if($fields[$i]){
					# print mrk format
					print "=$f  \\\\\$".$sub_f.$fields[$i]."\n";
				}
			}
			#}
		print "\n";
	}
close FH;
